qcacld-3.0: Fix implicit log declaration when !WLAN_DEBUG
Clang throws:
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.c:21652:9: error: implicit declaration of function 'hdd_ieee80211_reason_code_to_str' [-Werror,-Wimplicit-function-declaration]
                      hdd_ieee80211_reason_code_to_str(ieee80211_reason),
                      ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.c:21654:9: error: implicit declaration of function 'hdd_qca_reason_to_str' [-Werror,-Wimplicit-function-declaration]
                      hdd_qca_reason_to_str(adapter->last_disconnect_reason),
                      ^

Due to missing those logging functions, fix it by adding dummy functions
when WLAN_DEBUG is not used instead of wrapping it around the
translation so we can avoid other unnecessary conflicts in the future.

Fixes: 90d93d891c81ea18126e8a937b60119f3195ebeb ("qcacld-3.0: Have enum to string conversion APIs under DEBUG define")
Signed-off-by: Nauval Rizky <enuma.alrizky@gmail.com>